language: php
sudo: false
cache: composer

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
